import { createCipheriv, createDecipheriv, randomBytes } from 'crypto';
import { config } from '../config/env';

const ALGORITHM = 'aes-256-gcm';
// Defensively ensures the key is exactly 32 bytes, which AES-256 requires
const KEY = Buffer.from(config.encryptionKey, 'utf8').subarray(0, 32);

export function encrypt(plaintext: string): string {
  // 12 bytes is the cryptographic standard for GCM mode IVs
  const iv = randomBytes(12);
  const cipher = createCipheriv(ALGORITHM, KEY, iv);
  
  const encrypted = Buffer.concat([
    cipher.update(plaintext, 'utf8'), 
    cipher.final()
  ]);
  
  // Extracts the 16-byte authentication tag generated by GCM
  const tag = cipher.getAuthTag();
  
  return `${iv.toString('hex')}:${tag.toString('hex')}:${encrypted.toString('hex')}`;
}

export function decrypt(ciphertext: string): string {
  const [ivHex, tagHex, encryptedHex] = ciphertext.split(':');
  
  const iv = Buffer.from(ivHex, 'hex');
  const tag = Buffer.from(tagHex, 'hex');
  const encrypted = Buffer.from(encryptedHex, 'hex');
  
  const decipher = createDecipheriv(ALGORITHM, KEY, iv);
  
  // The AuthTag must be set before deciphering begins
  decipher.setAuthTag(tag);
  
  // CORRECTED: Safely concat the buffers before converting to a UTF-8 string
  // Previously, adding a Buffer to a string could cause encoding malformations
  const decrypted = Buffer.concat([
    decipher.update(encrypted), 
    decipher.final()
  ]);
  
  return decrypted.toString('utf8');
}